# Request: No input, the service will just return the last known coordinates
---
# Response: success (bool), message (string), and the last known coordinates (Point)
bool success
string message
sensor_msgs/PointCloud2 cloud

